### PR TITLE
Fix Variant Annotation Page and Tree page

### LINKED ISSUE #438: Variant annotation tab is not working
Probably because the tumor type structure has been changed

### PR DESCRIPTION
**Pull request by zhx828**
This will close #438 #440

### CODE REVIEW

File: web/yo/app/scripts/controllers/VariantCtrl.js [hunk 1]
```diff
@@ -430,13 +428,13 @@ angular.module('oncokbApp')
...
                     if ($scope.view.selectedSubtype) {
-                        var mappedSubtypes = findSubtypesByCancerType(n.cancerType);
+                        var mappedSubtypes = findSubtypesByCancerType(n.mainType.name);
                         if (!containSubtype($scope.view.selectedSubtype, mappedSubtypes)) {
                             $scope.view.filteredSubtypes = mappedSubtypes;
                             $scope.view.selectedSubtype = '';
                         }
                     } else {
-                        $scope.view.filteredSubtypes = findSubtypesByCancerType(n.cancerType);
+                        $scope.view.filteredSubtypes = findSubtypesByCancerType(n.mainTypeName);
```
Comment (JiaoJiao123) [inline web/yo/app/scripts/controllers/VariantCtrl.js]: should this be "n.mainType.name" instead of "n.mainTypeName"?

Comment (zhx828) [inline web/yo/app/scripts/controllers/VariantCtrl.js]: @JiaoJiao123 thanks! I updated the PR. If you think it's good, could you merge it?
