### PR TITLE
Fixed bugs

### LINKED ISSUE #401: Map `Truncating Mutations` when query for Deletion if not `Deletion` section curated in that gene

### PR DESCRIPTION
**Pull request by zhx828**
This will close #401 #402

### CODE REVIEW

File: core/src/test/java/org/mskcc/cbio/oncokb/util/IndicatorUtilsTest.java [hunk 1]
```diff
@@ -77,6 +69,48 @@ public void testProcessQuery() throws Exception {
...
+        resp2 = IndicatorUtils.processQuery(query2, null, null, null, false);
+        assertTrue("The oncogenicity should be the same", resp1.getOncogenic().equals(resp2.getOncogenic()));
+        assertTrue("The treatment should be the same", resp1.getTreatments().equals(resp2.getTreatments()));
+
+        // Match Loss with Deletion
+        query1 = new Query("PTEN", "Loss", null);
+        query2 = new Query("PTEN", "Deletion", null);
+        resp1 = IndicatorUtils.processQuery(query1, null, null, null, false);
+        resp2 = IndicatorUtils.processQuery(query2, null, null, null, false);
+        assertTrue("The oncogenicity should be the same", resp1.getOncogenic().equals(resp2.getOncogenic()));
```
Comment (JiaoJiao123) [inline core/src/test/java/org/mskcc/cbio/oncokb/util/IndicatorUtilsTest.java]: Could we change the message to something like "The oncogenicities are not the same"? 
I think the error message should describe what is the error precisely.  And same for the treatment message

Comment (zhx828) [inline core/src/test/java/org/mskcc/cbio/oncokb/util/IndicatorUtilsTest.java]: Sounds fare. I will change them.

File: core/src/test/java/org/mskcc/cbio/oncokb/util/IndicatorUtilsTest.java [hunk 2]
```diff
@@ -77,6 +69,48 @@ public void testProcessQuery() throws Exception {
...
+        resp2 = IndicatorUtils.processQuery(query2, null, null, null, false);
+        assertTrue("The oncogenicities are not the same.", resp1.getOncogenic().equals(resp2.getOncogenic()));
+        assertTrue("The treatments are not the same.", resp1.getTreatments().equals(resp2.getTreatments()));
+
+        // Match Loss with Deletion
+        query1 = new Query("PTEN", "Loss", null);
+        query2 = new Query("PTEN", "Deletion", null);
+        resp1 = IndicatorUtils.processQuery(query1, null, null, null, false);
+        resp2 = IndicatorUtils.processQuery(query2, null, null, null, false);
+        assertTrue("The oncogenicities are notthe same.", resp1.getOncogenic().equals(resp2.getOncogenic()));
```
Comment (JiaoJiao123) [inline core/src/test/java/org/mskcc/cbio/oncokb/util/IndicatorUtilsTest.java]: add a space between "notthe"
